# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Harald Sitter <sitter@kde.org>

# Partially a huge hack to work around https://github.com/systemd/mkosi/issues/4397
# This subimage produces nothing itself. Rather it gets mkosi to build a default initrd.
# We then manually unpack it here and prepare it for pickup by the actual UKI images.

# ALSO this is a convenient place to inject an initrd-exclusive relationship that runs udev trigger to load modules
# after the switch-root pivot into the sysroot.
# We only have the tiniest set of kernel modules in the initrd to get us out of initrd. All additional stuff such as GPU
# gets loaded after the switch-root. This allows us to keep all firmwars out of the initrd and consequently sport a reasonably sized
# unified kernel image.

[Output]
ImageVersion= # disable to get a stable name "initrd-build" without version or anything
Format=directory

[Content]
Initrds=default
MakeInitrd=yes
UnifiedKernelImages=no
Bootable=no
