# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Harald Sitter <sitter@kde.org>

[Output]
ImageVersion= # disable to get a stable name without version or anything
ImageId=kde-linux
Format=uki
ElTorito=no

[Config]
Dependencies=initrd-build

[Content]
BaseTrees=../../mkosi.output/initrd-build
UnifiedKernelImages=yes
Bootloader=uki
Bootable=yes
KernelCommandLine=
    rw rootflags=subvol=@system,compress=zstd:-4,lazytime
    lsm=landlock,lockdown,yama,integrity,bpf
    zswap.enabled=0
    preempt=full threadirqs
    nohz=on nohz_full=all
    rcu_nocbs=all rcutree.enable_rcu_lazy=1
    amdgpu.dcdebugmask=0x10
    systemd.hostname=kde-linux
    nowatchdog
    vt.global_cursor_default=0 quiet splash plymouth.ignore-serial-consoles loglevel=3
