version = 3

[[annotations]]
path = "mkosi.extra/usr/share/plymouth/themes/breeze-bgrt/*"
SPDX-FileCopyrightText = "Plymouth Developers"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "mkosi.extra/live/usr/calamares/desktop/branding/kde-linux/kde-symbolic.png"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "mkosi.extra/etc/issue"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
