version = 1

[[annotations]]
path = "mkosi.extra/usr/share/plymouth/themes/breeze-bgrt/*"
SPDX-FileCopyrightText = "Plymouth Developers"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "mkosi.extra/usr/share/factory/etc/xdg/kde-builder.yaml"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "mkosi.extra/live/usr/calamares/desktop/branding/kde-linux/kde-symbolic.png"
SPDX-FileCopyrightText = "2014 Uri Herrera <uri_herrera@nitrux.in> and others"
SPDX-License-Identifier = "LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL"

[[annotations]]
path = "mkosi.extra/etc/issue"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "mkosi.extra/usr/share/plymouth/plymouthd.defaults"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path="mkosi.extra/usr/lib/udev/rules.d/60-usb-dirty-pages-udev.rules"
SPDX-FileCopyrightText = "2023 Bruno Gonçalves <www.biglinux.com.br>"
SPDX-License-Identifier = "GPL-3.0-or-later"
