#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Lasath Fernando <devel@lasath.org>

set -eu

image=/run/kde-linux-incus/incus.btrfs

rm -rf /var/lib/incus
install -d -m 0711 /var/lib/incus
truncate -s 2G "$image"
mkfs.btrfs -f -L kde-linux-incus "$image"
mount -o loop,compress=zstd:1,noatime "$image" /var/lib/incus
