# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2026 Nate Graham <nate@kde.org>
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>

# Base system. Things we'll probably never want to remove no matter how
# much we strip it down and move content into Kapsule or elsewhere.

[Content]
Packages=
    # Base system: bootloader, kernel, firmware, and low-level libraries
    edk2-shell-x64
    glibc-all-langpacks # Fedora equivalent of glibc-locales
    microcode_ctl
    kmod
    kmscon
    linux-firmware
    kernel-headers # For DKMS
    kernel # It's the kernel!
    plymouth
    realtime-setup
    shim-x64
    systemd
    systemd-resolved
    systemd-ukify
    xdg-user-dirs
    zram-generator

    # HW enablement: graphics
    libva-intel-media-driver # Hardware accelerated video on newer Intel GPUs
    libva # Hardware accelerated video in general
    mesa-va-drivers # Hardware accelerated video on AMD GPUs
    libva-nvidia-driver
    mesa-dri-drivers
    # TODO: nvidia-open not in Fedora repos, use akmod-nvidia from RPM Fusion
    vulkan-loader
    mesa-vulkan-drivers # Covers intel, radeon, swrast

    # HW enablement: audio
    alsa-sof-firmware

    # HW enablement: printing
    cups
    cups-browsed
    foomatic-db
    gutenprint
    hplip
    ipp-usb
    system-config-printer

    # HW enablement: other
    pcsc-lite-acsccid
    android-tools # udev not needed anymore
    # WARNING: bmusb depends on a module that will make us fail secure boot review
    ccid
    fprintd
    iio-sensor-proxy
    apfs-fuse
    linux-firmware # covers marvell firmware and amd-microcode too
    lvm2
    # WARNING: openrazer-daemon will make use fail secure boot review
    pam-u2f
    powertop
    sane-backends # udev rules - everything else deleted later
    solaar-udev # solaar-udev for udev rules only
    steam-devices
    thermald
    tpm2-tss
    tuned-ppd # or power-profiles-daemon
    udev-hid-bpf-stable
    udisks2 # btrfs support included
    usb_modeswitch
    usbmuxd
    # WARNING: v4l2loopback-utils will make us fail secure boot review
    wireless-regdb
    # yubikey-full-disk-encryption not packaged in Fedora but systemd-cryptenroll can be used

    # Base system: CLI tools
    btrfsmaintenance
    btrfs-progs
    efibootmgr
    erofs-utils
    inotify-tools
    dosfstools
    e2fsprogs
    exfatprogs
    f2fs-tools
    fatresize
    mokutil
    ntfsprogs
    nvidia-gpu-firmware
    sbsigntools
    xfsprogs
    ydotool

    # App support
    flatpak
    fuse
    fuse3
    # WARNING:: vhba-module will make us fail secure boot review

    # Virtualization/VM integration
    dnsmasq
    edk2-ovmf
    open-vm-tools
    qemu-guest-agent
    spice-vdagent
    swtpm
    virtiofsd
    virtualbox-guest-additions
