# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2026 Nate Graham <nate@kde.org>
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>

# Base system. Things we'll probably never want to remove no matter how
# much we strip it down and move content into Kapsule or elsewhere.

[Content]
Packages=
    # Base system: bootloader, kernel, firmware, and low-level libraries
    amd-ucode
    edk2-shell
    glibc-all-langpacks # Fedora equivalent of glibc-locales
    intel-microcode # Fedora equivalent of intel-ucode
    kmod
    kmscon
    linux-firmware
    linux-headers # For DKMS
    kernel # It's the kernel!
    plymouth
    realtime-setup
    shim-x64
    systemd
    systemd-resolved
    systemd-ukify
    xdg-user-dirs
    zram-generator

    # HW enablement: graphics
    intel-media-driver # Hardware accelerated video on newer Intel GPUs
    libva # Hardware accelerated video in general
    libva-intel-driver # Hardware accelerated video on old Intel GPUs
    mesa-va-drivers # Hardware accelerated video on AMD GPUs
    libva-nvidia-driver
    mesa
    # TODO: nvidia-open not in Fedora repos, use akmod-nvidia from RPM Fusion
    vulkan-loader
    mesa-vulkan-drivers # Covers intel, radeon, swrast

    # HW enablement: audio
    sof-firmware

    # HW enablement: printing
    cups
    cups-browsed
    foomatic-db
    gutenprint
    hplip
    ipp-usb
    system-config-printer

    # HW enablement: other
    pcsc-lite-acsccid
    android-udev-rules # Fedora equivalent of android-udev
    # TODO: bmusb not packaged in Fedora
    ccid
    fprintd
    iio-sensor-proxy
    apfs-fuse
    linux-firmware # covers marvell firmware too
    lvm2
    # TODO: openrazer-daemon not in Fedora repos
    pam-u2f
    powertop
    sane-backends # udev rules - everything else deleted later
    solaar-udev # solaar-udev for udev rules only
    steam-devices
    thermald
    tpm2-tss
    tuned-ppd # or power-profiles-daemon
    udev-hid-bpf-stable
    udisks2 # btrfs support included
    usb_modeswitch
    usbmuxd
    # TODO: v4l2loopback-utils not packaged in Fedora, available via RPM Fusion
    wireless-regdb
    # TODO: yubikey-full-disk-encryption not packaged in Fedora

    # Base system: CLI tools
    btrfsmaintenance
    btrfs-progs
    efibootmgr
    erofs-utils
    inotify-tools
    dosfstools
    e2fsprogs
    exfatprogs
    f2fs-tools
    fatresize
    mokutil
    ntfsprogs
    nvidia-gpu-firmware
    sbsigntools
    xfsprogs
    ydotool

    # App support
    flatpak
    fuse
    fuse3
    # TODO: vhba-module not packaged in Fedora

    # Virtualization/VM integration
    dnsmasq
    edk2-ovmf
    open-vm-tools
    qemu-guest-agent
    spice-vdagent
    swtpm
    virtiofsd
    virtualbox-guest-additions
