# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2026 Nate Graham <nate@kde.org

# Base system. Things we'll probably never want to remove no matter how
# much we strip it down and move content into Kapsule or elsewhere.

[Content]
Packages=
    # Base system: bootloader, kernel, firmware, and low-level libraries
    kernel-modules-hook
    kmod
    kmscon # modern userspace getty and virtual terminal replacement
    linux-atm
    linux-firmware
    linux-zen-headers # For DKMS
    linux-zen # Improved Kernel
    plymouth
    realtime-privileges # `realtime` group and realtime privileges for processes using it
    systemd
    systemd-resolvconf
    systemd-sysvcompat
    systemd-ukify
    mkinitcpio
    zram-generator # use compressed zram for swap


    mesa
    vpl-gpu-rt # Hardware accelerated video on newer Intel GPUs
    vulkan-icd-loader
    vulkan-intel
    vulkan-radeon
    vulkan-swrast # Vulkan for old GPUs and some Virtual Machines


    # Base system: CLI tools that need to be on the base image; and why
    base # Base Arch packages; mandatory
    btrfs-progs # Btrfs tools; so system tools can interact with our disks
    busybox # Tiny rescue tools; for emergencies
    erofs-utils # Erofs tools; so system tools can interact with our OS image
    ydotool # Basic TUI and GUI app automation; needs low-level access to work
        # Candidates for removal once we have Kapsule-by-default: dev tools
    base-devel
    cmake
    meson # often used for glib software as alternative to cmake
    ninja
    systemd-bootchart # Boot profiling tools
    xz
