# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org

# Libraries, plugins, and tools that sit above the core and directly plug into
# KDE GUI software not shipped using Flatpak. Include this stuff with image
# until and unless we can bundle it all with the GUI software layer somehow.

[Content]
Packages=
    # Networking

    # Xor

    # Direct optional dependencies of KDE software in the FDO or KDE runtime.
    # Everything here should be listed in the "optdepends" array of something in
    # https://invent.kde.org/sysadmin/repo-metadata/-/blob/master/distro-dependencies/arch.yaml

    # Direct optional dependencies of KDE software NOT in the FDO or KDE runtime.
    # Everything here should be listed in the "optdepends" array of something in
    # https://invent.kde.org/sysadmin/repo-metadata/-/blob/master/distro-dependencies/arch.yaml

    libraw # kimageformats
    noto-fonts # Our base font, Noto
    switcheroo-control # kio, for launching apps on non-default GPU
