# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org>
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>
# Libraries, plugins, and tools that sit above the core and directly plug into
# KDE GUI software not shipped using Flatpak. Include this stuff with image
# until and unless we can bundle it all with the GUI software layer somehow.
[Content]
Packages=
    # Networking
    NetworkManager-strongswan # VPN support for NetworkManager
    NetworkManager-l2tp # VPN support for NetworkManager
    NetworkManager-openconnect # VPN support for NetworkManager
    NetworkManager-openvpn # VPN support for NetworkManager
    NetworkManager-pptp # VPN support for NetworkManager
    NetworkManager-sstp # VPN support for NetworkManager
    NetworkManager-vpnc # VPN support for NetworkManager
    nfs-utils # Support harness for NFS mounting
    nss-mdns # Needed for Avahi mDNS for local domain resolving etc.
    samba # For sharing local folders via Samba
    firewalld # Fedora default firewall; replaces ufw since plasma-firewall KCM supports firewalld

    # Audio
    pipewire
    pipewire-alsa
    pipewire-plugin-jack
    pipewire-plugin-libcamera
    pipewire-pulseaudio # Fedora equivalent of pipewire-pulse
    pipewire-module-ffado
    pipewire-module-roc
    pipewire-v4l2
    wireplumber

    # Xorg
    xorg-x11-server-Xwayland # Fedora equivalent of xorg-xwayland

    # Direct optional dependencies of KDE software in the FDO or KDE runtime.
    geoclue2 # Fedora equivalent of geoclue
    hunspell
    hunspell-en
    libavif
    libheif
    libjxl
    qt6-qtmultimedia # ffmpeg backend included on Fedora

    # Direct optional dependencies of KDE software NOT in the FDO or KDE runtime.
    arj
    bluez-obexd # Fedora equivalent of bluez-obex
    # TODO: bup not packaged in fedora
    catdoc
    fwupd
    jxrlib
    libappindicator-gtk3
    libdbusmenu-gtk3
    LibRaw
    # TODO: lrzip not packaged in Fedora
    lzop
    google-noto-fonts-common # Fedora equivalent of noto-fonts
    google-noto-cjk-fonts # Fedora equivalent of noto-fonts-cjk
    google-noto-emoji-fonts # Fedora equivalent of noto-fonts-emoji
    OpenEXR-libs # Fedora equivalent of openexr
    opus-tools
    quota # kdeplasma-addons, for Disk Quota widget
    rsync
    switcheroo-control
    tesseract-langpack-eng
    tesseract
    unrar
    xdg-desktop-portal-gtk
