# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org

# KDE software built from source in the last run of the packages pipeline.

[Content]
Packages=
    # KDE stuff we built using kde-builder in the packages pipeline
    # TODO: Remove once we have install tar
    @kde-desktop-environment
