# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org

# Direct optional dependencies of KDE software.
#
# Everything here should be listed in the "optdepends" array of something in
# https://invent.kde.org/sysadmin/repo-metadata/-/blob/master/distro-dependencies/arch.yaml

[Content]
Packages=
    appmenu-gtk-module # plasma-desktop, for global menu support in GTK 3 apps
    arj # ark, for ARJ archives
    bluez-obex # Bluetooth file sharing, through the KCM
    bup # kup, for one of the backends
    catdoc # kfilemetadata, for indexing old MS word docs
    cryfs # plasma-vault, for compatibility
    encfs # plasma-vault, for compatibility
    fwupd # for Discover backend
    geoclue # backend for QtPositioning, used for Night Light automatic location mode
    gocryptfs # plasma-vault, for new vaults
    hunspell # sonnet and KRunner's spellchecker plugin
    hunspell-en_us # hunspell requires at least one language backend; only English for now
    jxrlib # kimageformats
    libappimage # kio-extras, for AppImage app thumbnails
    libappindicator-gtk3 # plasma-desktop, for tray icon support in GTK 3 apps
    libavif # kimageformats
    libdbusmenu-gtk3 # plasma-desktop, for global menu support in GTK 3 apps
    libheif # kimageformats
    libjxl # kimageformats
    libraw # kimageformats
    lrzip # ark, for lzma, rzip, and zpaq compressed archives
    lzop # ark, for lzo compressed archives
    noto-fonts # Our base font, Noto
    noto-fonts-cjk # Noto CJK scripts
    noto-fonts-emoji # Noto emojis
    openexr # kimageformats
    opus-tools # audiocd-kio, opus encoding
    qt6-multimedia-ffmpeg # ffmpeg backend for qt6-multimedia, used in Dolphin, Konsole, Spectacle, and Prison
    quota-tools # kdeplasma-addons, for Disk Quota widget
    rsync # kup, for one of the backends
    switcheroo-control # kio, for launching apps on non-default GPU
    tesseract-data-eng # Tesseract requires at least one language backend; only English for now
    tesseract # Spectacle OCR
    unrar # ark, for RAR decompression support
