# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org

[Content]
Packages=
    arch-install-scripts
    boost
    boost-libs
    cmake
    glib2-devel
    pacman
    python-dbus
    python-evdev
    python-pyperclip
    python-pyte
    python-setuptools
    python-setproctitle # For kde-builder
    python-pyudev
    python-yaml # For kde-builder
    yaml-cpp
