# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org

[Content]
Packages=
    arch-install-scripts
    boost
    boost-libs
    cmake
    glib2-devel
    pacman
    python-setproctitle # For kde-builder
    python-yaml # For kde-builder
    yaml-cpp
