# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
#
# SPDX-FileCopyrightText: 2024 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2025 Kristen McWilliam <kristen@kde.org>
# SPDX-FileCopyrightText: 2026 Nate Graham <nate@kde.org

# CLI tools.

[Content]
Packages=
    # Basic tools we should always include
    iproute2 # Basic networking tools
    iw # Kernel-level wireless configuration
    vim
    zsh
    git
