# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
#
# SPDX-FileCopyrightText: 2024 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2025 Kristen McWilliam <kristen@kde.org>
# SPDX-FileCopyrightText: 2026 Nate Graham <nate@kde.org>
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>

# CLI tools.

[Content]
Packages=
    # Basic tools we should always include
    desktop-file-utils
    vim-minimal
    iproute
    iw
    less
    lsof
    nano
    openssh
    ripgrep
    tree
    unzip
    usbutils
    vim
    wget
    wl-clipboard
    xdg-utils
    zip
    zsh
    zsh-autosuggestions
    zsh-lovers # Fedora equivalent of zsh-completions
    # TODO: zsh-history-substring-search not packaged in Fedora
    zsh-syntax-highlighting

    # Candidates for removal once we have Kapsule-by-default: user tools
    alsa-utils
    android-tools
    bash-completion
    bat
    bluez
    # TODO: cdemu-client not packaged in Fedora
    cpupower # part of kernel-tools on Fedora
    drm_info
    duf
    espeak-ng
    fastfetch
    fd-find
    fzf
    git
    git-lfs
    gping
    htop
    iotop
    jq
    kdialog
    libratbag
    libva-utils
    lshw
    man-db
    man-pages
    mcfly
    nvme-cli
    nvtop
    plocate
    procs
    tldr
    trash-cli
    turbostat # part of kernel-tools on Fedora
    udftools
    wireguard-tools
    words
    yubikey-manager

    # Candidates for removal once we have Kapsule-by-default: dev tools
    bc
    ccache
    clang
    clazy
    cmake
    crun
    distrobox
    docker-ce # TODO: requires Docker CE repo, not in Fedora
    docker-buildx-plugin
    docker-compose-plugin
    flatpak-builder
    gperf
    intltool
    lldb
    llvm
    meson
    ninja-build
    perf
    perl-URI
    podman
    podman-compose
    python3-pyatspi
    python3-lxml
    qemu-system-x86
    reuse
    sassc
    strace
    systemd-bootchart
    subversion
    toolbox
    vulkan-headers
    xerces-c
    xz

    # Candidates for removal once we have Kapsule-by-default: tools for
    # building KDE Linux itself
    boost-devel
    cmake
    glib2-devel
    dracut
    python3-setproctitle
    python3-yaml
    ruby
    rubygems
    yaml-cpp
