#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2025 Thomas Duckworth <tduck@filotimoproject.org>

set -eu

if ! flatpak info org.mozilla.firefox >/dev/null 2>&1; then
  echo "The Firefox flatpak is not installed. Exiting." >&2
  exit 1
fi

# Ensure accent colors are correctly applied to Firefox.
flatpak override --system org.mozilla.firefox --filesystem=xdg-config/gtk-3.0:ro

# Install codecs-extra at runtime - this gets around distribution restrictions on codec licensing.
# This is required for Firefox to decode certain video formats.

# Make sure it installs the codecs-extra package for the correct runtime.
RUNTIME_REF="$(flatpak info org.mozilla.firefox 2>/dev/null | grep -E 'Runtime:' | awk '{print $2}')"
RUNTIME_ARCH="$(echo "$RUNTIME_REF" | cut -d'/' -f2)"
RUNTIME_BRANCH="$(echo "$RUNTIME_REF" | cut -d'/' -f3)"
CODEC_REF="org.freedesktop.Platform.codecs-extra/${RUNTIME_ARCH}/${RUNTIME_BRANCH}-extra"

if (! flatpak info "$CODEC_REF" &>/dev/null) && flatpak remote-info flathub "$CODEC_REF" &>/dev/null; then
    flatpak install --system --runtime -y "$CODEC_REF"
elif ! flatpak info org.freedesktop.Platform.codecs-extra &>/dev/null; then
    flatpak install --system --runtime -y org.freedesktop.Platform.codecs-extra
fi

# Install the KDE Linux default Firefox config into the Firefox flatpak system config extension.
# This enables hardware acceleration on NVIDIA but can break it on other cards,
# so this should only be done conditionally.
if nvidia-smi > /dev/null 2>&1; then
  mkdir -p "/var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/${RUNTIME_ARCH}/stable/defaults/pref/"
  cp -rf "/usr/share/firefox-config/00-kde-linux-default.js" "/var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/${RUNTIME_ARCH}/stable/defaults/pref/00-kde-linux-default.js"
else
  rm -rf "/var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/${RUNTIME_ARCH}/stable/defaults/pref/00-kde-linux-default.js"
fi

# Install the KDE Linux default Firefox policy into the Firefox flatpak system config extension.
# This installs the Plasma Browser Integration extension.
# This, however, has the unfortunate side effect of causing Firefox to show a "Your browser is being managed by your organization" message in the settings.
# See https://support.mozilla.org/en-US/kb/customizing-firefox-using-policiesjson
mkdir -p "/var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/${RUNTIME_ARCH}/stable/policies/"
cp -rf "/usr/share/firefox-config/policies.json" "/var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/${RUNTIME_ARCH}/stable/policies/policies.json"
