#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2025 Thomas Duckworth <tduck@filotimoproject.org>

set -eu

# Install codecs-extra at runtime - this gets around distribution restrictions on codec licensing.
# This is required for Firefox to decode certain video formats.
flatpak install --runtime -y org.freedesktop.Platform.codecs-extra

# Install the KDE Linux default Firefox config into the Firefox flatpak system config extension.
mkdir -p /var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/$(uname -m)/stable/defaults/pref/
cp -rf /usr/share/firefox-config/00-kde-linux-default.js /var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/$(uname -m)/stable/defaults/pref/
