#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023-2025 Harald Sitter <sitter@kde.org>
# SPDX-FileCopyrightText: 2026 Hadi Chokr <hadichokr@icloud.com>
set -ex
. /etc/os-release
kernel_version="$1"
if [ -z "$kernel_version" ]; then
  versions=(/usr/lib/modules/*)
  version="${versions[-1]}"
  kernel_version="$(basename "$version")"
fi
if [ -z "$kernel_version" ]; then
  echo "No kernel version specified/found"
  exit 1
fi

# Ensure all DKMS modules are built for this kernel before we generate the initramfs
if ! dkms autoinstall -k "$kernel_version"; then
  echo "Error: DKMS autoinstall failed" >&2
  exit 1
fi

# On Fedora we use dracut
cat <<- EOF > dracut.conf
add_dracutmodules+=" systemd systemd-initrd plymouth kernel-modules 90sd-shutdown 91systemd-extension "
add_drivers+=" overlay "
compress="zstd"
EOF

LIVE_CMDLINE="rw \
  systemd.volatile=overlay systemd.firstboot=false systemd.hostname=kde-linux kde-linux.live=1 plasma.live.user=live \
  lsm=landlock,lockdown,yama,integrity,bpf \
  zswap.enabled=0 \
  preempt=full threadirqs \
  nohz=on nohz_full=all \
  rcu_nocbs=all rcutree.enable_rcu_lazy=1 \
  amdgpu.dcdebugmask=0x10 \
  vt.global_cursor_default=0 quiet splash loglevel=3"

dracut --conf dracut.conf \
  --kver "$kernel_version" \
  --force \
  initrd-live

ukify build \
  --linux /usr/lib/modules/$kernel_version/vmlinuz \
  --initrd initrd-live \
  --cmdline "$LIVE_CMDLINE" \
  --output live.efi

# "preempt=full threadirqs" reduces latency especially for audio and gaming workflows.
# "nohz=on nohz_full=all" stops waking up a CPU more than once a second if it has fewer
# than 2 tasks. This reduces latency for userspace software and may also save power. The
# kernel requires at least one CPU to not be using this mode, but it will choose one for
# us. This requires nohz=on, which is the default, but we manually specify it here anyway
# because nohz_full=all needs it and we don't want that to break.
# "rcu_nocbs=all rcutree.enable_rcu_lazy=1" turns on batched/lazy RCU on all CPUs,
# reducing wake-ups and therefore power usage. rcu_nocbs=all is actually turned on
# automatically by nohz_full=all, but we manually specify it here anyway because
# rcutree.enable_rcu_lazy=1 needs it and we don't want that to break.
# amdgpu.dcdebugmask=0x10 works around https://gitlab.freedesktop.org/drm/amd/-/issues/4831

MAIN_CMDLINE="rw rootflags=subvol=@system,compress=zstd:-4,lazytime \
  lsm=landlock,lockdown,yama,integrity,bpf \
  zswap.enabled=0 \
  preempt=full threadirqs \
  nohz=on nohz_full=all \
  rcu_nocbs=all rcutree.enable_rcu_lazy=1 \
  amdgpu.dcdebugmask=0x10 \
  systemd.hostname=kde-linux \
  vt.global_cursor_default=0 quiet splash loglevel=3"

dracut --conf dracut.conf \
  --kver "$kernel_version" \
  --force \
  initrd-main

ukify build \
  --linux /usr/lib/modules/$kernel_version/vmlinuz \
  --initrd initrd-main \
  --cmdline "$MAIN_CMDLINE" \
  --output kde-linux.efi

# Mock artifact for upgrades, see build.sh
ukify build \
  --cmdline "kde-linux.erofs.silence" \
  --output erofs.addon.efi
