# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2025 Aleix Pol Gonzalez <aleix.pol@codethink.co.uk>
# SPDX-FileCopyrightText: 2026 Harald Sitter <sitter@kde.org>

# Unique project name
name: kde-linux-nvidia-legacy

# Required BuildStream version
min-version: 2.7

# Subdirectory where elements are stored
element-path: elements

# Options to specify for the project, these provide
# command line switches which control the behavior of
# conditional directives in the element.bst files.
#
options:
  arch:
    type: arch
    description: Machine architecture
    variable: arch
    values:
    - aarch64
    - x86_64
    - riscv64
  target_arch:
    type: arch
    description: Architecture
    variable: target_arch
    values:
    - aarch64
    - i686
    - x86_64
    - ppc64le
    - ppc64
    - riscv64
    - loongarch64

variables:
  sbindir: "%{bindir}"
  sysconfdir: "/etc"
  localstatedir: "/var"
  lib: "lib/%{gcc_triplet}"
  indep-libdir: "%{prefix}/lib"
  debugdir: "%{indep-libdir}/debug"
  sourcedir: "%{debugdir}/source"
  flatpak_xmldir: "%{prefix}/share/app-info/xmls"
  licensedir: "%{datadir}/licenses"
  project_licensedir: "%{licensedir}/%{project-name}"
  # Definition of variables related to machine architecture
  gcc_triplet: "%{gcc_arch}-linux-%{abi}"
  triplet: "%{arch}-unknown-linux-%{abi}"
  gcc_arch: "%{arch}"
  flatpak_arch: "%{arch}"
  abi: "gnu"

  (?):
  - target_arch == "x86_64":
      arch: "x86_64"
      linux-root: 4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709
  - target_arch == "i686":
      arch: "i686"
      # See https://wiki.debian.org/Multiarch/Tuples#Why_not_use_GNU_triplets.3F
      gcc_arch: "i386"
      flatpak_arch: "i386"
      linux-root: 44479540-F297-41B2-9AF7-D131D5F0458A
  - target_arch == "aarch64":
      arch: "aarch64"
      linux-root: B921B045-1DF0-41C3-AF44-4C6F280D3FAE
  - target_arch == "ppc64le":
      arch: "powerpc64le"
      gcc_arch: "powerpc64le"
      flatpak_arch: "ppc64le"
  - target_arch == "ppc64":
      arch: "powerpc64"
      gcc_arch: "powerpc64"
      flatpak_arch: "ppc64"
  - target_arch == "riscv64":
      arch: "riscv64"
      gcc_arch: "riscv64"
      linux-root: 72EC70A6-CF74-40E6-BD49-4BDA08E8F224
  - target_arch == "loongarch64":
      arch: "loongarch64"
      gcc_arch: "loongarch64"
      linux-root: 77055800-792c-4f94-b39a-98c91b762bb6

sandbox:
  build-arch: '%{arch}'

environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  sources:
  - patch
- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  sources:
  - git_repo

aliases:
  github: https://github.com/
  pypi: https://files.pythonhosted.org/packages/
  nvidia: https://us.download.nvidia.com/XFree86/

artifacts:
- url: https://buildstream.cache.kde-linux.haraldsitter.eu:11001

source-caches:
- url: https://buildstream.cache.kde-linux.haraldsitter.eu:11001
