# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Harald Sitter <sitter@kde.org>

[Output]
ImageId=kde-linux
SplitArtifacts=uki
Format=uki
ElTorito=no

[Content]
BaseTrees=../../buildstream-initrdfs
UnifiedKernelImages=yes
KernelInitrdModules=default
Bootloader=uki
Bootable=yes
MakeInitrd=yes
KernelCommandLine=
    rw
    systemd.volatile=overlay systemd.firstboot=false systemd.hostname=kde-linux kde-linux.live=1 plasma.live.user=live
    lsm=landlock,lockdown,yama,integrity,bpf
    zswap.enabled=0
    preempt=full threadirqs
    nohz=on nohz_full=all
    rcu_nocbs=all rcutree.enable_rcu_lazy=1
    amdgpu.dcdebugmask=0x10
    nowatchdog
    vt.global_cursor_default=0 quiet splash plymouth.ignore-serial-consoles loglevel=3
