# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Thomas Duckworth <tduck@filotimoproject.org>

[main]
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=kde-linux-power-saver
balanced=kde-linux-balanced
performance=kde-linux-performance

[battery]
balanced=kde-linux-balanced-battery
power-saver=kde-linux-power-saver-battery
